### ISSUE TITLE
Using ODM causes crash

### ISSUE THREAD

**Issue by p10tyr** [daniela-hase/onvif-server#5]
When I use ODM manager to try and find ONVIF devices it crashes the program 

```
Uncaught TypeError TypeError: probeType.indexOf is not a function
    at <anonymous> (/home/piotr/repos/onvif-server/src/onvif-server.js:389:51)
    at <anonymous> (/home/piotr/repos/onvif-server/node_modules/xml2js/lib/parser.js:304:18)
```

![image](https://github.com/user-attachments/assets/e5a4cbd7-0f81-4e42-a7e8-9cda24ec40b0)

**Comment by daniela-hase** [comment]
Merged, thanks a lot!
